---
- name: "Install k3s"
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download

- name: "Setup master node"
  hosts: master
  become: yes
  roles:
    - role: k3s/master

- name: "Setup nodes"
  hosts: node
  become: yes
  roles:
    - role: k3s/node

- name: "Setup infrastructure on master"
  hosts: master
  become: yes
  roles:
    - role: master-infra
  tags:
    - master-infra

- name: "Install services on k3s"
  hosts: master
  become: yes
  roles:
    - role: services
  tags:
    - services

- name: "Setup specifics on zimaboard"
  hosts: zimaboard
  become: yes
  roles:
    - role: zimaboard
  tags:
    - zimaboard

- name: "Setup specifics for picam"
  hosts: picam
  become: yes
  roles:
    - role: picam
  tags:
    - picam
