---
- name: restart systemd-logind
  ansible.builtin.systemd:
    name: systemd-logind
    state: restarted

- name: restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
