---
- name: Create Gitlab Registry Credentials Secret
  kubernetes.core.k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    namespace: conways-game-of-life
    state: present
    definition:
      kind: Secret
      apiVersion: v1
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: gitlab-registry-credentials
      data:
        .dockerconfigjson: "{{ lookup('template', './dockerconfig.json.j2') | to_json | b64encode }}"

- name: Create a Service Account
  kubernetes.core.k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    namespace: default
    state: present
    definition:
      kind: ServiceAccount
      apiVersion: v1
      metadata:
        name: deployer-service-account

- name: Create a ClusterRoleBinding for cluster-admin role
  kubernetes.core.k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    namespace: default
    state: present
    definition:
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: deployer-service-account-cluster-admin
      roleRef:
        kind: ClusterRole
        name: cluster-admin
        apiGroup: rbac.authorization.k8s.io
      subjects:
        - kind: ServiceAccount
          name: deployer-service-account
          namespace: default

- name: Create Service Account Token
  kubernetes.core.k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    namespace: default
    state: present
    definition:
      apiVersion: v1
      type: kubernetes.io/service-account-token
      kind: Secret
      metadata:
        name: deployer-service-account-token
        annotations:
          kubernetes.io/service-account.name: deployer-service-account
