---
- name: Create a Service Account
  k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    namespace: default
    state: present
    definition:
      kind: ServiceAccount
      apiVersion: v1
      metadata:
        name: deployer-service-account

- name: Create a ClusterRoleBinding for cluster-admin role
  k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    namespace: default
    state: present
    definition:
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: deployer-service-account-cluster-admin
      roleRef:
        kind: ClusterRole
        name: cluster-admin
        apiGroup: rbac.authorization.k8s.io
      subjects:
        - kind: ServiceAccount
          name: deployer-service-account
          namespace: default

- name: Create Service Account Token
  k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    namespace: default
    state: present
    definition:
      apiVersion: v1
      type: kubernetes.io/service-account-token
      kind: Secret
      metadata:
        name: deployer-service-account-token
        annotations:
          kubernetes.io/service-account.name: deployer-service-account
