---
- name: Download Velero CLI
  get_url:
    url: https://github.com/vmware-tanzu/velero/releases/download/{{ velero_version }}/velero-{{ velero_version }}-linux-amd64.tar.gz
    dest: /tmp/velero.tar.gz
    mode: 0755

- name: Extract Velero binary
  unarchive:
    src: /tmp/velero.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move Velero binary to /usr/local/bin
  command: mv /tmp/velero-{{ velero_version }}-linux-amd64/velero /usr/local/bin/

- name: Set executable permissions on Velero binary
  file:
    path: /usr/local/bin/velero
    mode: "0755"

- name: Remove intermediate velero folder
  file:
    path: /tmp/velero-{{ velero_version }}-linux-amd64
    state: absent

- name: Create Velero Namespace
  kubernetes.core.k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: velero

- name: Create temporary File for Velero SA Key
  copy:
    dest: "{{ velero_gcp_sa_key_temporary_location }}"
    content: "{{ velero_gcp_sa_key }}"
    mode: "0600"

- name: Install Velero
  shell:
    cmd: >
      velero install \
        --kubeconfig /home/{{ ansible_user }}/.kube/config \
        --provider gcp \
        --plugins velero/velero-plugin-for-gcp:v1.9.0 \
        --bucket {{ velero_gcp_bucket }} \
        --use-volume-snapshots=false \
        --use-node-agent \
        --default-volumes-to-fs-backup \
        --secret-file {{ velero_gcp_sa_key_temporary_location }}
  args:
    executable: /bin/bash

- name: Remove temporary SA Key File
  file:
    path: "{{ velero_gcp_sa_key_temporary_location }}"
    state: absent

- name: Create Velero Backup Schedule
  kubernetes.core.k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    namespace: velero
    definition:
      apiVersion: velero.io/v1
      kind: Schedule
      metadata:
        name: full-cluster-backup
      spec:
        schedule: 0 3 * * 1
        ttl: 7d
        template:
          includeClusterResources: true
          storageLocation: default
