{
 "title": "BTRFS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uuid",
    "query": {
     "query": "label_values(node_btrfs_info,uuid)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(node_btrfs_device_errors_total,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_btrfs_device_errors_total{device=~\"$device\", uuid=\"$uuid\"}",
     "legendFormat": "{{type}} {{device}}"
    }
   ]
  },
  {
   "title": "Commits Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_btrfs_commits_total{uuid=\"$uuid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Unused Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by(device) (node_btrfs_device_unused_bytes{uuid=\"$uuid\", device=~\"$device\"}) / 1000000000",
     "legendFormat": "{{device}} unused"
    }
   ]
  },
  {
   "title": "Commit seconds total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_btrfs_commit_seconds_total{uuid=\"$uuid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}