{
 "title": "Internet Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_duration_seconds) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "speedtest_download_bytes*8", "legendFormat": "Download Speed" }
   ]
  },
  {
   "title": "Upstream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "speedtest_upload_bytes*8", "legendFormat": "Upload Speed" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "speedtest_latency_seconds", "legendFormat": "Latency" }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "speedtest_jittter_seconds", "legendFormat": "Jitter" }
   ]
  }
 ]
}