---
- name: Install NFS Server
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present

- name: Setup NFS Media Directory
  ansible.builtin.file:
    path: "{{ zimaboard_nfs_media_directory }}"
    owner: nobody
    group: nogroup
    state: directory

- name: Setup NFS Export Configuration
  ansible.builtin.template:
    src: "exports.j2"
    dest: "/etc/exports"
    owner: root
    group: root

- name: Increase inotify Limits
  ansible.builtin.command: sysctl fs.inotify.max_user_watches=131072
  become: true
