---
- name: Create Firefly-III namespace
  k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: firefly

- name: Create Firefly-III Secrets
  k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    namespace: firefly
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: firefly-secrets
      data:
        DB_PASSWORD: "{{ firefly_iii_postres_password|b64encode }}"
        DB_ADMIN_PASSWORD: "{{ firefly_iii_postres_admin_password|b64encode }}"
        APP_KEY: "{{ firefly_iii_app_key|b64encode }}"

- name: Create Firefly-III
  k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    namespace: firefly
    definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: firefly
      spec:
        repo: https://firefly-iii.github.io/kubernetes
        chart: firefly-iii
        targetNamespace: firefly
        valuesContent: |-
          ingress:
            annotations:
              kubernetes.io/ingress.class: "traefik"
              cert-manager.io/cluster-issuer: internal-issuer
              traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
            tls:
              - secretName: firefly-tls
                hosts:
                  - firefly.{{ domain }}
          config:
            env:
              DB_CONNECTION: pgsql
              DB_HOST: firefly-postgresql.firefly.svc.cluster.local
              DB_PORT: "5432"
              DB_DATABASE: firefly
              DB_USERNAME: firefly
              DEFAULT_LANGUAGE: "en_US"
              DEFAULT_LOCALE: "equal"
              TZ: "Europe/Berlin"
              TRUSTED_PROXIES: "**"
            existingSecret: firefly-secrets

- name: Create Firefly-III Database
  k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    namespace: firefly
    definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: firefly-database
      spec:
        repo: https://charts.bitnami.com/bitnami
        chart: postgresql
        valuesContent: |-
          image:
            tag: 15.3.0-debian-11-r17
          auth:
            username: firefly
            database: firefly
            existingSecret: firefly-secrets 
            secretKeys:
              adminPasswordKey: DB_ADMIN_PASSWORD
              userPasswordKey: DB_PASSWORD
          primary:
            persistence:
              storageClass: local-path
              size: 20Gi
