---
- include_tasks: tls.yml
- include_tasks: kubernetes-dashboard.yml
- include_tasks: postgres.yml
- include_tasks: pgadmin.yml
- include_tasks: grafana.yml
- include_tasks: traefik-dashboard.yml
- include_tasks: miniflux.yml
- include_tasks: recipes.yml
- include_tasks: longhorn-ui.yml
# - include_tasks: firefly-iii.yml
